import AppKit
import Foundation

@main
struct ClipboardStoreChecks {
    struct CheckFailure: Error, CustomStringConvertible {
        let description: String
    }

    @MainActor
    static func main() throws {
        let root = FileManager.default.temporaryDirectory
            .appendingPathComponent("PanoChecks-\(UUID().uuidString)", isDirectory: true)
        let suite = "PanoChecks.\(UUID().uuidString)"
        let defaults = UserDefaults(suiteName: suite)!
        let pasteboard = NSPasteboard.withUniqueName()
        defer {
            defaults.removePersistentDomain(forName: suite)
            pasteboard.releaseGlobally()
            try? FileManager.default.removeItem(at: root)
        }

        let historyURL = root.appendingPathComponent("history.json")
        pasteboard.setString("Predates app launch", forType: .string)
        let store = ClipboardStore(
            storageURL: historyURL,
            pasteboard: pasteboard,
            defaults: defaults,
            startMonitoring: false
        )
        store.checkForChanges()
        try check(store.entries.isEmpty, "Existing clipboard must not be imported")
        try check(!store.clipboardAccessDenied, "Isolated test pasteboard must be accessible")

        store.add(text: " \n\t ", sourceApp: "Checks")
        store.add(text: String(repeating: "a", count: 256 * 1_024 + 1), sourceApp: "Checks")
        try check(store.entries.isEmpty, "Blank and oversized values must be rejected")
        store.add(text: "  first\n", sourceApp: "Checks", at: Date(timeIntervalSince1970: 1))
        let firstID = store.entries[0].id
        store.togglePin(store.entries[0])
        store.add(text: "second", sourceApp: "Checks")
        store.add(text: "  first\n", sourceApp: "Updated", at: Date(timeIntervalSince1970: 3))
        try check(store.entries.count == 2, "Exact duplicate must not add a row")
        try check(store.entries[0].id == firstID && store.entries[0].isPinned, "Duplicate must retain identity and pin")
        try check(store.entries[0].text == "  first\n", "Original text whitespace must be preserved")
        try check(store.entries[0].sourceApp == "Updated", "Duplicate must update source metadata")

        for index in 0..<205 {
            store.add(text: "Entry \(index)", sourceApp: "Checks")
        }
        try check(store.entries.filter { !$0.isPinned }.count == 200, "History must cap unpinned entries at 200")
        try check(store.entries.contains { $0.id == firstID && $0.isPinned }, "Pinned entry must survive retention")
        try check(!store.entries.contains { $0.text == "Entry 0" }, "Oldest unpinned entries must be removed")

        let reloaded = ClipboardStore(storageURL: historyURL, pasteboard: pasteboard, defaults: defaults, startMonitoring: false)
        try check(reloaded.entries == store.entries, "Persisted history must round-trip")
        let attributes = try FileManager.default.attributesOfItem(atPath: historyURL.path)
        try check((attributes[.posixPermissions] as? NSNumber)?.intValue == 0o600, "History file must be owner-readable only")

        store.clearHistory()
        try check(store.entries.count == 1 && store.entries[0].isPinned, "Clear history must preserve pins")
        store.delete(store.entries[0])
        try check(store.entries.isEmpty, "Individual deletion must remove a pinned entry")

        try write("Fresh copy", to: pasteboard)
        store.checkForChanges()
        try check(store.entries.first?.text == "Fresh copy", "New clipboard text must be captured")
        let copiedID = store.entries[0].id
        try check(store.copy(store.entries[0]), "Copy must report successful clipboard writes")
        store.checkForChanges()
        try check(store.entries.count == 1 && store.entries[0].id == copiedID, "Own copies must retain one entry")
        try check(pasteboard.string(forType: .string) == "Fresh copy", "Copy must populate the clipboard")

        store.isPaused = true
        try write("While paused", to: pasteboard)
        store.checkForChanges()
        try check(store.entries.count == 1, "Paused copies must be discarded")
        try write("Also paused", to: pasteboard)
        store.isPaused = false
        store.checkForChanges()
        try check(store.entries.count == 1, "Resume must not import skipped copies")
        try write("After resume", to: pasteboard)
        store.checkForChanges()
        try check(store.entries.first?.text == "After resume", "Future copies must be captured after resume")

        for marker in [
            "org.nspasteboard.TransientType", "org.nspasteboard.ConcealedType",
            "org.nspasteboard.AutoGeneratedType", "com.agilebits.onepassword"
        ] {
            let previousCount = store.entries.count
            try write("Private test value \(marker)", to: pasteboard, marker: marker)
            store.checkForChanges()
            try check(store.entries.count == previousCount, "Private pasteboard markers must be ignored")
        }

        store.isPaused = true
        let pausedReload = ClipboardStore(storageURL: historyURL, pasteboard: pasteboard, defaults: defaults, startMonitoring: false)
        try check(pausedReload.isPaused, "Pause preference must persist")
        store.isPaused = false
        store.togglePin(store.entries[0])
        store.clearAll()
        try check(store.entries.isEmpty, "Clear all must remove every entry")

        try write("Predates restarted monitoring", to: pasteboard)
        store.startMonitoring()
        store.checkForChanges()
        store.stopMonitoring()
        try check(store.entries.isEmpty, "Starting monitoring must snapshot the current clipboard")

        try Data("invalid json".utf8).write(to: historyURL)
        let invalid = ClipboardStore(storageURL: historyURL, pasteboard: pasteboard, defaults: defaults, startMonitoring: false)
        try check(invalid.entries.isEmpty && invalid.storageError != nil, "Unreadable history must surface an error without crashing")

        let obstructedURL = root.appendingPathComponent("not-a-directory")
        try Data().write(to: obstructedURL)
        let unwritable = ClipboardStore(storageURL: obstructedURL.appendingPathComponent("history.json"), pasteboard: pasteboard, defaults: defaults, startMonitoring: false)
        unwritable.add(text: "Retained in memory", sourceApp: "Checks")
        try check(unwritable.entries.count == 1 && unwritable.storageError != nil, "Save failures must preserve the current session and surface an error")
        try checkPinboards(root: root, pasteboard: pasteboard, defaults: defaults)
        try checkLegacyHistory(root: root, pasteboard: pasteboard, defaults: defaults)
        try checkImageSupport(root: root, pasteboard: pasteboard, defaults: defaults)
        print("ClipboardStore checks passed.")
    }

    @MainActor
    static func checkPinboards(root: URL, pasteboard: NSPasteboard, defaults: UserDefaults) throws {
        let historyURL = root.appendingPathComponent("pinboard-checks/history.json")
        let store = ClipboardStore(storageURL: historyURL, pasteboard: pasteboard, defaults: defaults, startMonitoring: false)
        try check(store.pinboards.isEmpty, "New stores must not contain sample collections")
        try check(store.createPinboard(name: " \n ") == nil, "Blank collection names must be rejected")
        try check(store.createPinboard(name: String(repeating: "x", count: 41)) == nil, "Collection names must be limited to 40 characters")
        guard let work = store.createPinboard(name: "  Work  ", colorHex: 0x123456),
              let personal = store.createPinboard(name: "Personal") else {
            throw CheckFailure(description: "Valid collections must be created")
        }
        try check(work.name == "Work" && work.colorHex == 0x123456, "Collection names must be trimmed and colors preserved")
        try check(store.createPinboard(name: "WORK") == nil, "Case-insensitive duplicate collection names must be rejected")
        try check(!store.renamePinboard(personal, name: "work"), "Renaming must reject duplicate collection names")
        try check(!store.renamePinboard(personal, name: "  "), "Renaming must reject empty collection names")
        try check(store.renamePinboard(work, name: " Projects "), "Valid collection rename must succeed")
        try check(store.pinboards.first?.id == work.id && store.pinboards.first?.name == "Projects", "Renaming must retain collection identity")
        store.setPinboardColor(work, colorHex: 0x654321)
        try check(store.pinboards.first?.colorHex == 0x654321, "Collection color changes must retain the chosen color")

        store.add(text: "Board-kept snippet", sourceApp: "Checks")
        let boardEntry = store.entries[0]
        store.toggleMembership(boardEntry, in: work)
        store.toggleMembership(boardEntry, in: personal)
        store.setLabel(boardEntry, label: "  Reusable snippet  ")
        store.add(text: boardEntry.text, sourceApp: "Updated")
        try check(store.entries[0].pinboardIDs == Set([work.id, personal.id]), "Duplicates must retain every collection membership")
        try check(store.entries[0].label == "Reusable snippet", "Duplicates must retain the trimmed label")
        try check(!store.entries[0].isPinned, "Collection membership must remain separate from favorites")
        try check(store.copy(store.entries[0]), "Collection entry must copy successfully")
        try check(store.entries[0].pinboardIDs == Set([work.id, personal.id]) && store.entries[0].label == "Reusable snippet", "Copy must preserve collection and label metadata")

        store.add(text: "Favorite-kept snippet", sourceApp: "Checks")
        store.togglePin(store.entries[0])
        for index in 0..<205 {
            store.add(text: "Retention item \(index)", sourceApp: "Checks")
        }
        try check(store.entries.count == 202, "Retention must keep 200 ordinary items plus favorites and collection items")
        try check(store.entries.contains { $0.id == boardEntry.id }, "Collection items must survive retention")
        try check(store.entries.contains { $0.isPinned }, "Favorites must survive retention alongside collection items")
        store.clearHistory()
        try check(store.entries.count == 2, "Clear history must preserve favorites and collection items")

        let reloaded = ClipboardStore(storageURL: historyURL, pasteboard: pasteboard, defaults: defaults, startMonitoring: false)
        try check(reloaded.pinboards == store.pinboards, "Collections must persist across launches")
        try check(reloaded.entries == store.entries, "Collection membership and labels must persist across launches")
        let boardFile = historyURL.deletingLastPathComponent().appendingPathComponent("pinboards.json")
        let attributes = try FileManager.default.attributesOfItem(atPath: boardFile.path)
        try check((attributes[.posixPermissions] as? NSNumber)?.intValue == 0o600, "Collection file must be owner-readable only")

        store.toggleMembership(boardEntry, in: personal)
        try check(store.entries.first(where: { $0.id == boardEntry.id })?.pinboardIDs == Set([work.id]), "Membership toggle must affect only the chosen collection")
        store.deletePinboard(work)
        try check(store.entries.count == 2, "Deleting a collection must not delete its clipboard items")
        try check(store.entries.first(where: { $0.id == boardEntry.id })?.pinboardIDs.isEmpty == true, "Deleting a collection must remove its memberships")
        try check(store.pinboards.count == 1 && store.pinboards[0].id == personal.id, "Deleting a collection must preserve other collections")
        store.setLabel(boardEntry, label: " \n ")
        try check(store.entries.first(where: { $0.id == boardEntry.id })?.label == nil, "Blank labels must clear the label")
        store.clearHistory()
        try check(store.entries.count == 1 && store.entries[0].isPinned, "Former collection items must return to ordinary history")

        let afterDeletion = ClipboardStore(storageURL: historyURL, pasteboard: pasteboard, defaults: defaults, startMonitoring: false)
        try check(afterDeletion.pinboards == store.pinboards && afterDeletion.entries == store.entries, "Collection deletion must persist")
    }

    @MainActor
    static func checkLegacyHistory(root: URL, pasteboard: NSPasteboard, defaults: UserDefaults) throws {
        let legacyURL = root.appendingPathComponent("legacy/history.json")
        try FileManager.default.createDirectory(at: legacyURL.deletingLastPathComponent(), withIntermediateDirectories: true)
        let legacyID = UUID()
        let legacyJSON = """
        [{"id":"\(legacyID.uuidString)","text":"Previously saved text","copiedAt":0,"sourceApp":"Checks","isPinned":true}]
        """
        try Data(legacyJSON.utf8).write(to: legacyURL)
        let store = ClipboardStore(storageURL: legacyURL, pasteboard: pasteboard, defaults: defaults, startMonitoring: false)
        try check(store.entries.count == 1 && store.entries[0].id == legacyID, "Old history must load with its original identity")
        try check(store.entries[0].isPinned && store.entries[0].pinboardIDs.isEmpty && store.entries[0].label == nil, "Old favorites must retain their state and receive empty new metadata")
        store.setLabel(store.entries[0], label: "Migrated")
        let reloaded = ClipboardStore(storageURL: legacyURL, pasteboard: pasteboard, defaults: defaults, startMonitoring: false)
        try check(reloaded.entries.first?.label == "Migrated" && reloaded.entries.first?.text == "Previously saved text", "Migrated history must save without losing its text")
    }

    @MainActor
    static func checkImageSupport(root: URL, pasteboard: NSPasteboard, defaults: UserDefaults) throws {
        let historyURL = root.appendingPathComponent("image-checks/history.json")
        let store = ClipboardStore(storageURL: historyURL, pasteboard: pasteboard, defaults: defaults, startMonitoring: false)

        // Create a small test PNG (1x1 red pixel)
        let image = NSImage(size: NSSize(width: 2, height: 2))
        image.lockFocus()
        NSColor.red.drawSwatch(in: NSRect(x: 0, y: 0, width: 2, height: 2))
        image.unlockFocus()
        guard let tiffData = image.tiffRepresentation,
              let bitmapRep = NSBitmapImageRep(data: tiffData),
              let pngData = bitmapRep.representation(using: .png, properties: [:]) else {
            throw CheckFailure(description: "Failed to create test PNG data")
        }

        // Test: Add image via addImage
        store.addImage(imageData: pngData, sourceApp: "ImageTest")
        try check(store.entries.count == 1, "Image must be added to entries")
        try check(store.entries[0].imageFilename != nil, "Image entry must have a filename")
        try check(store.entries[0].imageFilename != nil, "Image entry must be recognized as image")
        let imageFilename = store.entries[0].imageFilename!
        let imageURL = store.imagesDirectory.appendingPathComponent(imageFilename)
        try check(FileManager.default.fileExists(atPath: imageURL.path), "Image file must be saved to disk")

        // Test: Load image
        let loadedImage = store.loadImage(for: store.entries[0])
        try check(loadedImage != nil, "Saved image must be loadable")

        // Test: Copy image to pasteboard
        try check(store.copy(store.entries[0]), "Image copy must succeed")
        let pastedData = pasteboard.data(forType: .png)
        try check(pastedData != nil && !pastedData!.isEmpty, "Image must be placed on pasteboard as PNG")

        // Test: Image persistence
        let reloaded = ClipboardStore(storageURL: historyURL, pasteboard: pasteboard, defaults: defaults, startMonitoring: false)
        try check(reloaded.entries.count == 1, "Image entry must persist across reloads")
        try check(reloaded.entries[0].imageFilename == imageFilename, "Image filename must persist")

        // Test: Delete cleans up image file
        store.delete(store.entries[0])
        try check(store.entries.isEmpty, "Delete must remove image entry")
        try check(!FileManager.default.fileExists(atPath: imageURL.path), "Delete must clean up image file")

        // Test: Empty image data is rejected
        store.addImage(imageData: Data(), sourceApp: "ImageTest")
        try check(store.entries.isEmpty, "Empty image data must be rejected")

        // Test: Oversized image data is rejected
        let oversizedData = Data(repeating: 0xFF, count: 10 * 1_024 * 1_024 + 1)
        store.addImage(imageData: oversizedData, sourceApp: "ImageTest")
        try check(store.entries.isEmpty, "Oversized image data must be rejected")

        // Test: Image entries alongside text entries
        store.addImage(imageData: pngData, sourceApp: "ImageTest")
        store.add(text: "Text alongside image", sourceApp: "TextTest")
        try check(store.entries.count == 2, "Text and image entries must coexist")
        try check(store.entries[0].imageFilename == nil, "Most recent text entry must be first")
        try check(store.entries[1].imageFilename != nil, "Image entry must follow text")

        // Test: clearAll cleans up image files
        let imageFile2 = store.entries[1].imageFilename!
        let imageURL2 = store.imagesDirectory.appendingPathComponent(imageFile2)
        try check(FileManager.default.fileExists(atPath: imageURL2.path), "Image file must exist before clearAll")
        store.clearAll()
        try check(store.entries.isEmpty, "clearAll must remove all entries")
        try check(!FileManager.default.fileExists(atPath: imageURL2.path), "clearAll must clean up image files")
    }

    static func check(_ condition: @autoclosure () -> Bool, _ message: String) throws {
        if !condition() { throw CheckFailure(description: message) }
    }

    @MainActor
    static func write(_ text: String, to pasteboard: NSPasteboard, marker: String? = nil) throws {
        let item = NSPasteboardItem()
        item.setString(text, forType: .string)
        if let marker {
            item.setData(Data(), forType: NSPasteboard.PasteboardType(marker))
        }
        pasteboard.clearContents()
        try check(pasteboard.writeObjects([item]), "Test clipboard write failed")
    }
}
